name: Daily Saudi Report

on:
  schedule:
    - cron: '0 14 * * *'   # 14:00 UTC = 17:00 بتوقيت الرياض
  workflow_dispatch:     # لتشغيل يدوي

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Report
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python daily_saudi_report.py
